source "https://rubygems.org"

gem "rack"
gem "json"
gem "pry"
gem "pry-byebug"
gem "puma"
gem "sequel"
gem "pg"
gem "bunny"

group :test do
  gem "sqlite3"
  gem "rspec"
  gem "rack-test"
  gem "webmock"
end
