services:
  postgres_auth:
    image: postgres:15
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: fudo
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: fudo
    volumes:
      - pgdata_auth:/var/lib/postgresql/data

  postgres_product:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: fudo
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: fudo
    ports:
      - "5433:5432"
    volumes:
      - pgdata_product:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"    # para servicios
      - "15672:15672"  # UI web
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  auth-service:
    build:
      context: ./services/auth-service
    env_file:
      - ./services/auth-service/.env
    working_dir: /app
    volumes:
      - ./services/auth-service:/app
    ports:
      - "4000:4000"
    depends_on:
      - postgres_auth
    stdin_open: true
    tty: true

  product-service:
    build:
      context: ./services/product-service
    env_file:
      - ./services/product-service/.env
    working_dir: /app
    volumes:
      - ./services/product-service:/app
    ports:
      - "4001:4000"
    depends_on:
      - postgres_product
      - rabbitmq
    stdin_open: true
    tty: true

  product_creation_worker:
    build:
      context: ./services/product-service
    env_file:
      - ./services/product-service/.env
    command: ruby workers/product_creation_worker.rb
    working_dir: /app
    volumes:
      - ./services/product-service:/app
    depends_on:
      - postgres_product
      - rabbitmq
    stdin_open: true
    tty: true
    deploy:
      replicas: 2

  api-gateway:
    build:
      context: ./services/api-gateway
    env_file:
      - ./services/api-gateway/.env
    working_dir: /app
    volumes:
      - ./services/api-gateway:/app
    ports:
      - "8080:4000"
    depends_on:
      - auth-service
      - product-service
    stdin_open: true
    tty: true

volumes:
  pgdata_auth:
  pgdata_product:
