module AppConfig
  DB_HOST = ENV.fetch("DB_HOST")
  DB_USER = ENV.fetch("DB_USER")
  DB_PASS = ENV.fetch("DB_PASS")
  DB_NAME = ENV.fetch("DB_NAME")
  RABBITMQ_HOST = ENV.fetch("RABBITMQ_HOST")
  RABBITMQ_PORT = ENV.fetch("RABBITMQ_PORT")
  RABBITMQ_USER = ENV.fetch("RABBITMQ_USER")
  RABBITMQ_PASS = ENV.fetch("RABBITMQ_PASS")
  INTERNAL_API_SECRET = ENV.fetch("INTERNAL_API_SECRET")
end
